[build]
  command = "npm run build"
  publish = ".vista/deploy/netlify"
  functions = "netlify/functions"

[functions]
  node_bundler = "none"
  included_files = ["netlify/functions/.vista/**", "netlify/functions/node_modules/**"]

[dev]
  command = "npm run dev"
  port = 3003

[[redirects]]
  from = "/_vista/*"
  to = "/_vista/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
