import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const cloudflareAdapter: DeploymentAdapter = {
  name: 'cloudflare',
  description: 'Cloudflare Workers and Pages deployment adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir, debug } = context;

    // Primary output: .vista/cloudflare/ (the worker entry used by wrangler)
    const outputDir = path.join(vistaDir, 'cloudflare');
    fs.mkdirSync(outputDir, { recursive: true });

    // Deploy artefacts: .vista/deploy/cloudflare/ (checked by test-vista-deploy)
    const deployDir = path.join(vistaDir, 'deploy', 'cloudflare');
    fs.mkdirSync(deployDir, { recursive: true });

    const workerScript = `// Auto-generated by Vista Cloudflare Workers Adapter
// Run 'vista build' first to emit the Vista edge router bundle at
// .vista/cloudflare/server.js — this worker dynamically imports it.

export default {
  async fetch(request, env, ctx) {
    // 1. Serve static assets from the ASSETS binding (Cloudflare Pages / Workers Sites)
    if (env.ASSETS) {
      try {
        const assetResponse = await env.ASSETS.fetch(request);
        if (assetResponse.status !== 404) {
          return assetResponse;
        }
      } catch {
        // ASSETS binding not configured — continue to router
      }
    }

    // 2. Dispatch to the Vista edge router bundle (emitted by vista build)
    try {
      const { handleRequest } = await import('./server');
      if (typeof handleRequest === 'function') {
        return handleRequest(request, env, ctx);
      }
    } catch (e) {
      // Router bundle not present — instruct the developer to run vista build
      console.error('[vista:cloudflare] Could not load router bundle:', e && e.message);
    }

    return new Response(
      JSON.stringify({
        error: 'Vista edge bundle not found. Run: vista build --adapter cloudflare',
      }),
      { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }
};
`;

    fs.writeFileSync(path.join(outputDir, '_worker.js'), workerScript);
    // Also write to deploy dir so callers find it at the canonical path
    fs.writeFileSync(path.join(deployDir, '_worker.js'), workerScript);

    // _routes.json: route inclusion/exclusion manifest for Cloudflare Pages
    const routesJson = JSON.stringify({
      version: 1,
      include: ['/*'],
      exclude: ['/static/*', '/_vista/*'],
    }, null, 2);
    fs.writeFileSync(path.join(deployDir, '_routes.json'), routesJson);

    const wranglerConfig = `# Auto-generated by Vista Cloudflare Adapter
name = "vista-app"
main = ".vista/cloudflare/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vista/static"
`;

    // Always write wrangler.toml to the project root (--force semantics)
    fs.writeFileSync(path.join(cwd, 'wrangler.toml'), wranglerConfig);
    fs.writeFileSync(path.join(outputDir, 'wrangler.toml'), wranglerConfig);
    fs.writeFileSync(path.join(deployDir, 'wrangler.toml'), wranglerConfig);

    if (debug) {
      console.log('[vista:deploy] Generated Cloudflare Workers output at .vista/cloudflare/_worker.js');
      console.log('[vista:deploy] Generated Cloudflare deploy artefacts at .vista/deploy/cloudflare/');
    }
  },
};
