import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const cloudflareAdapter: DeploymentAdapter = {
  name: 'cloudflare',
  description: 'Cloudflare Workers and Pages deployment adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir, debug } = context;
    const outputDir = path.join(vistaDir, 'cloudflare');
    fs.mkdirSync(outputDir, { recursive: true });

    // The generated worker serves static assets via the ASSETS binding and
    // falls through to the Vista router bundle. The router bundle is emitted
    // by `vista build --adapter cloudflare` as `.vista/cloudflare/server.js`.
    // We use a dynamic import so wrangler only fails at bundle-time (not deploy-
    // time) when the build step has not been run yet.
    const workerScript = `// Auto-generated by Vista Cloudflare Workers Adapter
// Run 'vista build' first to emit the Vista edge router bundle at
// .vista/cloudflare/server.js — this worker dynamically imports it.

export default {
  async fetch(request, env, ctx) {
    // 1. Serve static assets from the ASSETS binding (Cloudflare Pages / Workers Sites)
    if (env.ASSETS) {
      try {
        const assetResponse = await env.ASSETS.fetch(request);
        if (assetResponse.status !== 404) {
          return assetResponse;
        }
      } catch {
        // ASSETS binding not configured — continue to router
      }
    }

    // 2. Dispatch to the Vista edge router bundle (emitted by vista build)
    try {
      const { handleRequest } = await import('./server');
      if (typeof handleRequest === 'function') {
        return handleRequest(request, env, ctx);
      }
    } catch (e) {
      // Router bundle not present — instruct the developer to run vista build
      console.error('[vista:cloudflare] Could not load router bundle:', e && e.message);
    }

    return new Response(
      JSON.stringify({
        error: 'Vista edge bundle not found. Run: vista build --adapter cloudflare',
      }),
      { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }
};
`;


    fs.writeFileSync(path.join(outputDir, '_worker.js'), workerScript);

    const wranglerConfig = `# Auto-generated by Vista Cloudflare Adapter
name = "vista-app"
main = ".vista/cloudflare/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vista/static"
`;

    const rootWrangler = path.join(cwd, 'wrangler.toml');
    if (!fs.existsSync(rootWrangler)) {
      fs.writeFileSync(rootWrangler, wranglerConfig);
    }
    fs.writeFileSync(path.join(outputDir, 'wrangler.toml'), wranglerConfig);

    if (debug) {
      console.log('[vista:deploy] Generated Cloudflare Workers output at .vista/cloudflare/_worker.js');
    }
  },
};
