import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const cloudflareAdapter: DeploymentAdapter = {
  name: 'cloudflare',
  description: 'Cloudflare Workers and Pages deployment adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir, debug } = context;
    const outputDir = path.join(vistaDir, 'cloudflare');
    fs.mkdirSync(outputDir, { recursive: true });

    // The generated worker dispatches requests to the Vista router entry which is
    // expected to be bundled at .vista/cloudflare/server.js by the Vista build step.
    // Static assets are served first; dynamic requests fall through to the router.
    const workerScript = `// Auto-generated by Vista Cloudflare Workers Adapter
// This worker serves static assets first, then dispatches to the Vista router.
import { handleRequest } from './server';

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 1. Serve static assets from the ASSETS binding (Cloudflare Pages / Workers Sites)
    if (env.ASSETS) {
      const assetResponse = await env.ASSETS.fetch(request);
      if (assetResponse.status !== 404) {
        return assetResponse;
      }
    }

    // 2. Dispatch to the Vista edge router
    // The handleRequest export is produced by vista build and wraps app/api routes.
    if (typeof handleRequest === 'function') {
      return handleRequest(request, env, ctx);
    }

    // Fallback: 404 if no router bundle is present (build step may not have run)
    return new Response(
      JSON.stringify({ error: 'Vista server bundle not found. Run vista build first.' }),
      { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }
};
`;


    fs.writeFileSync(path.join(outputDir, '_worker.js'), workerScript);

    const wranglerConfig = `# Auto-generated by Vista Cloudflare Adapter
name = "vista-app"
main = ".vista/cloudflare/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".vista/static"
`;

    const rootWrangler = path.join(cwd, 'wrangler.toml');
    if (!fs.existsSync(rootWrangler)) {
      fs.writeFileSync(rootWrangler, wranglerConfig);
    }
    fs.writeFileSync(path.join(outputDir, 'wrangler.toml'), wranglerConfig);

    if (debug) {
      console.log('[vista:deploy] Generated Cloudflare Workers output at .vista/cloudflare/_worker.js');
    }
  },
};
