import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const netlifyAdapter: DeploymentAdapter = {
  name: 'netlify',
  description: 'Netlify Edge Functions and static hosting adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir, debug } = context;
    const netlifyDeployDir = path.join(vistaDir, 'deploy', 'netlify');

    fs.mkdirSync(netlifyDeployDir, { recursive: true });

    // _redirects: SPA fallback and /_vista/* asset rewrite
    const redirects = [
      '/_vista/* /_vista/:splat 200',
      '/api/* /.netlify/functions/api/:splat 200',
      '/* /index.html 200',
    ].join('\n');
    fs.writeFileSync(path.join(netlifyDeployDir, '_redirects'), redirects + '\n');

    // netlify.toml: build settings and functions directory
    const netlifyToml = `# Auto-generated by Vista Netlify Adapter
[build]
  command = "vista build"
  publish = ".vista/static"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;
    fs.writeFileSync(path.join(cwd, 'netlify.toml'), netlifyToml);

    if (debug) {
      console.log('[vista:deploy] Generated Netlify deployment config at netlify.toml');
      console.log('[vista:deploy] Generated Netlify redirects at .vista/deploy/netlify/_redirects');
    }
  },
};
