import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const nodeAdapter: DeploymentAdapter = {
  name: 'node',
  description: 'Node.js standalone production server adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir } = context;
    const standaloneDir = path.join(vistaDir, 'standalone');
    fs.mkdirSync(standaloneDir, { recursive: true });

    const serverPath = path.join(standaloneDir, 'server.js');
    // If Vista's core standalone builder already generated server.js, preserve it
    if (fs.existsSync(serverPath)) {
      if (context.debug) {
        console.log('[vista:deploy] Existing standalone server.js preserved.');
      }
      return;
    }

    const serverScript = `// Auto-generated by Vista Node.js Deployment Adapter
const path = require('path');
const process = require('process');

const port = Number(process.env.PORT) || 3000;

try {
  // startServer is exported from dist/server/engine and accepts (port: number)
  const { startServer } = require('../server/engine');
  startServer(port);
  console.log(\`[vista:standalone] Server listening on port \${port}\`);
} catch (err) {
  console.error('[vista:standalone] Failed to start server:', err);
  process.exit(1);
}
`;


    fs.writeFileSync(serverPath, serverScript);
    if (context.debug) {
      console.log('[vista:deploy] Generated Node.js standalone server at .vista/standalone/server.js');
    }
  },
};
