import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

export const nodeAdapter: DeploymentAdapter = {
  name: 'node',
  description: 'Node.js standalone production server adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir } = context;
    const standaloneDir = path.join(vistaDir, 'standalone');
    fs.mkdirSync(standaloneDir, { recursive: true });

    const serverPath = path.join(standaloneDir, 'server.js');
    // If Vista's core standalone builder already generated server.js, preserve it
    if (fs.existsSync(serverPath)) {
      if (context.debug) {
        console.log('[vista:deploy] Existing standalone server.js preserved.');
      }
      return;
    }

    const serverScript = `// Auto-generated by Vista Node.js Deployment Adapter
// This file requires the Vista standalone build to have been run first.
// Run: vista build   (or: vista build --adapter node)
// The build step populates .vista/ with the compiled server assets.

const path = require('path');
const process = require('process');

const port = Number(process.env.PORT) || 3000;

// Locate the Vista server entry relative to the standalone directory.
// The real server bundle is placed at .vista/server/engine.js by vista build.
const enginePath = path.resolve(__dirname, '../server/engine');

try {
  const engine = require(enginePath);

  if (typeof engine.startServer === 'function') {
    engine.startServer(port);
    console.log('[vista:standalone] Server listening on port ' + port);
  } else if (typeof engine.createRequestHandler === 'function') {
    const http = require('http');
    const handler = engine.createRequestHandler({ cwd: process.cwd() });
    http.createServer(handler).listen(port, () => {
      console.log('[vista:standalone] Server listening on port ' + port);
    });
  } else {
    console.error('[vista:standalone] Engine does not export startServer or createRequestHandler');
    console.error('[vista:standalone] Did you run vista build first?');
    process.exit(1);
  }
} catch (err) {
  console.error('[vista:standalone] Failed to start server:', err.message);
  console.error('[vista:standalone] Ensure you ran: vista build');
  process.exit(1);
}
`;



    fs.writeFileSync(serverPath, serverScript);
    if (context.debug) {
      console.log('[vista:deploy] Generated Node.js standalone server at .vista/standalone/server.js');
    }
  },
};
