import fs from 'fs';
import path from 'path';
import type { DeploymentAdapter, DeploymentContext } from './types';

function copyDirectoryRecursive(sourceDir: string, targetDir: string): void {
  if (!fs.existsSync(sourceDir)) return;
  fs.mkdirSync(targetDir, { recursive: true });
  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const from = path.join(sourceDir, entry.name);
    const to = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      copyDirectoryRecursive(from, to);
    } else if (entry.isFile()) {
      fs.copyFileSync(from, to);
    }
  }
}

export const vercelAdapter: DeploymentAdapter = {
  name: 'vercel',
  description: 'Vercel Serverless and Build Output API v3 adapter',
  build(context: DeploymentContext): void {
    const { cwd, vistaDir, debug } = context;
    const vercelOutputDir = path.join(cwd, '.vercel', 'output');
    const vercelStaticDir = path.join(vercelOutputDir, 'static');
    const vercelFunctionsDir = path.join(vercelOutputDir, 'functions');

    fs.rmSync(vercelOutputDir, { recursive: true, force: true });
    fs.mkdirSync(vercelStaticDir, { recursive: true });

    // Public assets & static output
    copyDirectoryRecursive(path.join(cwd, 'public'), vercelStaticDir);
    copyDirectoryRecursive(path.join(vistaDir, 'static'), path.join(vercelStaticDir, 'static'));

    const clientCssPath = path.join(vistaDir, 'client.css');
    if (fs.existsSync(clientCssPath)) {
      fs.copyFileSync(clientCssPath, path.join(vercelStaticDir, 'client.css'));
      fs.copyFileSync(clientCssPath, path.join(vercelStaticDir, 'styles.css'));
    }

    // ------------------------------------------------------------------
    // Serverless function entry for dynamic SSR + API routes
    // Placed at functions/api.func — Vercel routes /api/** and SSR paths here.
    // ------------------------------------------------------------------
    const apiFuncDir = path.join(vercelFunctionsDir, 'api.func');
    fs.mkdirSync(apiFuncDir, { recursive: true });

    // .vc-config.json tells Vercel this is a Node.js serverless function
    fs.writeFileSync(
      path.join(apiFuncDir, '.vc-config.json'),
      JSON.stringify({ runtime: 'nodejs20.x', handler: 'index.js', launcherType: 'Nodejs' }, null, 2)
    );

    // The function handler: boots Vista's server engine to handle the request.
    // Path from .vercel/output/functions/api.func/index.js to project root is ../../../../
    const apiFuncHandler = `// Auto-generated by Vista Vercel Adapter
// This serverless function handles dynamic API routes and SSR.
let _handler;

function getHandler() {
  if (!_handler) {
    // The engine entry is at <projectRoot>/.vista/server/engine.js
    // From .vercel/output/functions/api.func/ we go up 4 directories to project root
    try {
      const enginePath = require('path').resolve(__dirname, '../../../../.vista/server/engine');
      const engine = require(enginePath);

      if (typeof engine.createRequestHandler === 'function') {
        _handler = engine.createRequestHandler({ cwd: process.cwd() });
      } else {
        console.error('[vista:vercel] Engine does not export createRequestHandler');
        _handler = (_req, res) => {
          res.statusCode = 503;
          res.end(JSON.stringify({ error: 'Vista engine not compatible with serverless mode' }));
        };
      }
    } catch (loadErr) {
      // Log the diagnostic server-side; do not expose internal paths to the client
      console.error('[vista:vercel] Failed to load engine:', loadErr && loadErr.message);
      _handler = (_req, res) => {
        res.statusCode = 503;
        res.end(JSON.stringify({ error: 'Vista server not available. Run vista build first.' }));
      };
    }
  }
  return _handler;
}

module.exports = async (req, res) => {
  try {
    await getHandler()(req, res);
  } catch (err) {
    // Log internally; return a generic error payload to avoid leaking stack traces
    console.error('[vista:vercel] Unhandled error:', err && err.message);
    if (!res.headersSent) {
      res.statusCode = 500;
      res.end(JSON.stringify({ error: 'Internal server error' }));
    }
  }
};
`;


    fs.writeFileSync(path.join(apiFuncDir, 'index.js'), apiFuncHandler);

    const config = {
      version: 3,
      routes: [
        { handle: 'filesystem' },
        { src: '^/_vista/(.*)$', dest: '/$1' },
        { src: '^/(?:rsc|_rsc)/?$', dest: '/static/pages/index.rsc' },
        { src: '^/(?:rsc|_rsc)/(.+)$', dest: '/static/pages/$1.rsc' },
        // Dynamic API and SSR routes → serverless function
        { src: '^/api(/.*)?$', dest: '/api' },
        { src: '^/$', dest: '/static/pages/index.html' },
        { src: '^/(.+)$', dest: '/static/pages/$1.html' },
      ],
    };

    fs.writeFileSync(path.join(vercelOutputDir, 'config.json'), JSON.stringify(config, null, 2));

    if (debug) {
      console.log('[vista:deploy] Generated Vercel Build Output v3 at .vercel/output/');
      console.log('[vista:deploy] Generated serverless function at .vercel/output/functions/api.func/');
    }
  },
};
